import type {
  SurfaceNode, UnitNode, DataConnectNode, FeelRuleNode,
  HealDirectiveNode, SecureDirectiveNode, ConditionNode,
  OnDirectiveNode, LayoutDirectiveNode,
} from './ast.js';

export interface CodegenOptions {
  runtime?:  string;
  target?:   'ts' | 'js';   // default 'js' — emit ESM JS directly
  comments?: boolean;
}

// ── generateSurface ────────────────────────────────────────────────────
// Compiles a SurfaceNode to either TypeScript (target:'ts') or
// optimized ESM JavaScript (target:'js', default).
// The JS output skips the TypeScript compile step entirely — like Svelte.

export function generateSurface(node: SurfaceNode, opts: CodegenOptions = {}): string {
  const runtime  = opts.runtime ?? '@drishti/runtime';
  const target   = opts.target  ?? 'js';
  const isTS     = target === 'ts';
  const lines: string[] = [];

  const header = isTS
    ? `// Generated by DRISHTI Compiler — DO NOT EDIT\nimport { createSurface, createUnit } from '${runtime}';\nimport type { SurfaceDef, UnitDef } from '${runtime}';\n`
    : `// Generated by DRISHTI Compiler — DO NOT EDIT\nimport { createSurface, createUnit } from '${runtime}';\n`;

  lines.push(header);
  lines.push(`export const ${node.name} = createSurface({`);

  if (node.intent)  lines.push(`  intent: ${JSON.stringify(node.intent)},`);
  if (node.secure)  lines.push(`  secure: ${generateSecure(node.secure)},`);
  if (node.layout)  lines.push(`  layout: ${generateLayout(node.layout)},`);

  if (node.genome?.length) {
    const genome = node.genome.reduce<Record<string, string>>((acc, g) => {
      acc[g.key] = g.value; return acc;
    }, {});
    lines.push(`  genome: ${JSON.stringify(genome)},`);
  }

  if (node.on.length) lines.push(`  on: [${node.on.map(generateOn).join(', ')}],`);

  lines.push('  units: [');
  for (const unit of node.units) {
    const unitCode = generateUnit(unit, isTS).split('\n').map(l => `    ${l}`).join('\n');
    lines.push(`${unitCode},`);
  }
  lines.push('  ],');

  lines.push(isTS ? `}${isTS ? ' satisfies SurfaceDef' : ''});` : '});');
  lines.push('');

  return lines.join('\n');
}

// ── generateUnit ───────────────────────────────────────────────────────
function generateUnit(node: UnitNode, isTS: boolean): string {
  const parts: string[] = [];
  parts.push('createUnit({');
  parts.push(`  name: ${JSON.stringify(node.name)},`);
  if (node.data)          parts.push(`  data: ${generateData(node.data)},`);
  if (node.columns?.length) parts.push(`  columns: ${JSON.stringify(node.columns)},`);
  if (node.feel.length)   parts.push(`  feel: [${node.feel.map(generateFeel).join(', ')}],`);
  if (node.heal)          parts.push(`  heal: ${generateHeal(node.heal)},`);
  if (node.secure)        parts.push(`  secure: ${generateSecure(node.secure)},`);
  if (node.adapt)         parts.push(`  adapt: ${JSON.stringify(node.adapt.source)},`);
  if (node.predict)       parts.push(`  predict: ${JSON.stringify(node.predict.target)},`);
  if (node.layout)        parts.push(`  layout: ${generateLayout(node.layout)},`);
  if (node.on.length)     parts.push(`  on: [${node.on.map(generateOn).join(', ')}],`);
  if (Object.keys(node.props).length) parts.push(`  props: ${JSON.stringify(node.props)},`);
  if (isTS) parts.push(`  // @ts-ignore — generated code`);
  parts.push('})');
  return parts.join('\n');
}

// ── Helpers ────────────────────────────────────────────────────────────

function generateData(node: DataConnectNode): string {
  return JSON.stringify({ source: node.source, realtime: node.realtime });
}

function generateFeel(node: FeelRuleNode): string {
  const obj: Record<string, unknown> = { emotion: node.emotion };
  if (node.condition) obj['condition'] = generateConditionObj(node.condition);
  return JSON.stringify(obj);
}

function generateConditionObj(c: ConditionNode): Record<string, string> {
  const obj: Record<string, string> = { left: c.left, op: c.operator };
  if (c.right !== undefined) obj['right'] = c.right;
  return obj;
}

function generateHeal(node: HealDirectiveNode): string {
  const obj: Record<string, unknown> = { mode: node.mode };
  if (node.retries !== undefined) obj['retries'] = node.retries;
  if (node.fallbackLabel)         obj['fallback'] = node.fallbackLabel;
  return JSON.stringify(obj);
}

function generateSecure(node: SecureDirectiveNode): string {
  return JSON.stringify({ requirement: node.requirement, args: node.args });
}

function generateLayout(node: LayoutDirectiveNode): string {
  return JSON.stringify({ type: node.type, ...(node.value !== undefined ? { value: node.value } : {}) });
}

function generateOn(node: OnDirectiveNode): string {
  return JSON.stringify({ event: node.event, action: node.action });
}
