import type {
  SurfaceNode, UnitNode, DataConnectNode, FeelRuleNode,
  HealDirectiveNode, SecureDirectiveNode, ConditionNode,
  OnDirectiveNode, LayoutDirectiveNode,
} from './ast.js';

export interface CodegenOptions {
  runtime?:  string;
  target?:   'ts' | 'js';   // default 'js' — emit ESM JS directly
  comments?: boolean;
  mode?:     'dom' | 'ssr' | 'hydrate';
  minify?:   boolean;
}

export interface CodegenResult {
  code: string;
  imports: string[];
  exports: string[];
}

export interface ASTExpr {
  type: 'signal' | 'static' | 'event';
  value: string;
}

export interface DOMASTNode {
  type: 'element' | 'text' | 'expression' | 'component' | 'fragment';
  tag?: string;
  attrs?: Record<string, string | ASTExpr>;
  children?: DOMASTNode[];
  value?: string;
  expr?: ASTExpr;
}

/**
 * Generate direct DOM creation code (no vdom overhead).
 * Input: a simple AST node (as produced by the parser).
 * Output: TypeScript code using document.createElement, etc.
 */
export function generateDirectDOM(ast: DOMASTNode, opts?: CodegenOptions): CodegenResult {
  const lines: string[] = [];
  let counter = 0;

  function nextId(): number {
    return counter++;
  }

  function processNode(node: DOMASTNode): string {
    if (node.type === 'text') {
      const id = nextId();
      const varName = `t_${id}`;
      const escaped = (node.value ?? '').replace(/\\/g, '\\\\').replace(/'/g, "\\'");
      lines.push(`  const ${varName} = document.createTextNode('${escaped}');`);
      return varName;
    }

    if (node.type === 'element') {
      const id = nextId();
      const varName = `el_${id}`;
      lines.push(`  const ${varName} = document.createElement('${node.tag ?? 'div'}');`);

      // Process attrs
      if (node.attrs) {
        for (const [attrName, attrVal] of Object.entries(node.attrs)) {
          if (typeof attrVal === 'string') {
            // static string attr
            lines.push(`  ${varName}.setAttribute('${attrName}', '${attrVal.replace(/'/g, "\\'")}');`);
          } else if (attrVal.type === 'event') {
            // event handler
            const eventName = attrName.startsWith('on:') ? attrName.slice(3) : attrName;
            lines.push(`  ${varName}.addEventListener('${eventName}', ${attrVal.value});`);
          } else if (attrVal.type === 'signal') {
            // reactive signal attr
            lines.push(`  effect(() => { ${varName}.setAttribute('${attrName}', ${attrVal.value}()); });`);
          } else {
            // static expr
            lines.push(`  ${varName}.setAttribute('${attrName}', ${attrVal.value});`);
          }
        }
      }

      // Process children
      if (node.children) {
        for (const child of node.children) {
          const childVar = processNode(child);
          lines.push(`  ${varName}.appendChild(${childVar});`);
        }
      }

      return varName;
    }

    if (node.type === 'fragment') {
      const id = nextId();
      const varName = `frag_${id}`;
      lines.push(`  const ${varName} = document.createDocumentFragment();`);
      if (node.children) {
        for (const child of node.children) {
          const childVar = processNode(child);
          lines.push(`  ${varName}.appendChild(${childVar});`);
        }
      }
      return varName;
    }

    if (node.type === 'expression') {
      const id = nextId();
      const varName = `t_${id}`;
      const exprVal = node.expr ? `${node.expr.value}()` : "''";
      lines.push(`  const ${varName} = document.createTextNode(String(${exprVal}));`);
      if (node.expr?.type === 'signal') {
        lines.push(`  effect(() => { ${varName}.textContent = String(${node.expr!.value}()); });`);
      }
      return varName;
    }

    // component — placeholder
    const id = nextId();
    const varName = `el_${id}`;
    lines.push(`  const ${varName} = document.createElement('div');`);
    return varName;
  }

  const rootVar = processNode(ast);
  lines.push(`  return ${rootVar};`);

  const fnBody = lines.join('\n');
  const code = `function render() {\n${fnBody}\n}`;

  return {
    code,
    imports: ['signal', 'effect', 'h'],
    exports: ['render'],
  };
}

// ── generateSurface ────────────────────────────────────────────────────
// Compiles a SurfaceNode to either TypeScript (target:'ts') or
// optimized ESM JavaScript (target:'js', default).
// The JS output skips the TypeScript compile step entirely — like Svelte.

export function generateSurface(node: SurfaceNode, opts: CodegenOptions = {}): string {
  const runtime  = opts.runtime ?? '@drishti/runtime';
  const target   = opts.target  ?? 'js';
  const isTS     = target === 'ts';
  const lines: string[] = [];

  const header = isTS
    ? `// Generated by DRISHTI Compiler — DO NOT EDIT\nimport { createSurface, createUnit } from '${runtime}';\nimport type { SurfaceDef, UnitDef } from '${runtime}';\n`
    : `// Generated by DRISHTI Compiler — DO NOT EDIT\nimport { createSurface, createUnit } from '${runtime}';\n`;

  lines.push(header);
  lines.push(`export const ${node.name} = createSurface({`);

  if (node.intent)  lines.push(`  intent: ${JSON.stringify(node.intent)},`);
  if (node.secure)  lines.push(`  secure: ${generateSecure(node.secure)},`);
  if (node.layout)  lines.push(`  layout: ${generateLayout(node.layout)},`);

  if (node.genome?.length) {
    const genome = node.genome.reduce<Record<string, string>>((acc, g) => {
      acc[g.key] = g.value; return acc;
    }, {});
    lines.push(`  genome: ${JSON.stringify(genome)},`);
  }

  if (node.on.length) lines.push(`  on: [${node.on.map(generateOn).join(', ')}],`);

  lines.push('  units: [');
  for (const unit of node.units) {
    const unitCode = generateUnit(unit, isTS).split('\n').map(l => `    ${l}`).join('\n');
    lines.push(`${unitCode},`);
  }
  lines.push('  ],');

  lines.push(isTS ? `}${isTS ? ' satisfies SurfaceDef' : ''});` : '});');
  lines.push('');

  return lines.join('\n');
}

// ── generateUnit ───────────────────────────────────────────────────────
function generateUnit(node: UnitNode, isTS: boolean): string {
  const parts: string[] = [];
  parts.push('createUnit({');
  parts.push(`  name: ${JSON.stringify(node.name)},`);
  if (node.data)          parts.push(`  data: ${generateData(node.data)},`);
  if (node.columns?.length) parts.push(`  columns: ${JSON.stringify(node.columns)},`);
  if (node.feel.length)   parts.push(`  feel: [${node.feel.map(generateFeel).join(', ')}],`);
  if (node.heal)          parts.push(`  heal: ${generateHeal(node.heal)},`);
  if (node.secure)        parts.push(`  secure: ${generateSecure(node.secure)},`);
  if (node.adapt)         parts.push(`  adapt: ${JSON.stringify(node.adapt.source)},`);
  if (node.predict)       parts.push(`  predict: ${JSON.stringify(node.predict.target)},`);
  if (node.layout)        parts.push(`  layout: ${generateLayout(node.layout)},`);
  if (node.on.length)     parts.push(`  on: [${node.on.map(generateOn).join(', ')}],`);
  if (Object.keys(node.props).length) parts.push(`  props: ${JSON.stringify(node.props)},`);
  if (isTS) parts.push(`  // @ts-ignore — generated code`);
  parts.push('})');
  return parts.join('\n');
}

// ── Helpers ────────────────────────────────────────────────────────────

function generateData(node: DataConnectNode): string {
  return JSON.stringify({ source: node.source, realtime: node.realtime });
}

function generateFeel(node: FeelRuleNode): string {
  const obj: Record<string, unknown> = { emotion: node.emotion };
  if (node.condition) obj['condition'] = generateConditionObj(node.condition);
  return JSON.stringify(obj);
}

function generateConditionObj(c: ConditionNode): Record<string, string> {
  const obj: Record<string, string> = { left: c.left, op: c.operator };
  if (c.right !== undefined) obj['right'] = c.right;
  return obj;
}

function generateHeal(node: HealDirectiveNode): string {
  const obj: Record<string, unknown> = { mode: node.mode };
  if (node.retries !== undefined) obj['retries'] = node.retries;
  if (node.fallbackLabel)         obj['fallback'] = node.fallbackLabel;
  return JSON.stringify(obj);
}

function generateSecure(node: SecureDirectiveNode): string {
  return JSON.stringify({ requirement: node.requirement, args: node.args });
}

function generateLayout(node: LayoutDirectiveNode): string {
  return JSON.stringify({ type: node.type, ...(node.value !== undefined ? { value: node.value } : {}) });
}

function generateOn(node: OnDirectiveNode): string {
  return JSON.stringify({ event: node.event, action: node.action });
}
